<form>
    <label for="name">Nome Completo</label>
    <input name="name" type="text"></input>
    </br>
    <label for="email">E-mail</label>
    <input name="email" type="text"></input>
    </br>
    <label for="rg">RG</label>
    <input name="rg" type="text"></input>
    </br>
    <label for="organ">Órgão Expelidor</label>
    <input name="organ" type="text"></input>
    </br>
    <label for="cpf">CPF</label>
    <input name="cpf" type="text"></input>
    </br>
    <label for="complete_address">Endereço Completo</label>
    <input name="complete_address" type="text"></input>
    </br>
    <label for="registration">Número de Matrícula</label>
    <input name="registration" type="text"></input>
    </br>
    <label for="marital_status">Estado Civil</label>
    <input name="marital_status" type="text"></input>
    </br>
    <label for="course">Curso</label>
    <input name="course" type="text"></input>
    </br>
    <label for="start_date">Início do Período de Participação</label>
    <input name="start_date" type="date"></input>
    </br>
    <label for="end_date">Fim do Período de Participação</label>
    <input name="end_date" type="text"></input>
    </br>
    <label for="position">Cargo Atual</label>
    <input name="position" type="text"></input>
    </br>
</form>
