<form>
    <div class="element-form">
        <label class="">Nome Completo</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">E-mail</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">RG/Órgão Expedidor</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">CPF</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Endereço Completo</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Número de Matrícula</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Estado Civil</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Telefones</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Curso</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Cargos Ocupados</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Início do Período de Participação</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Fim do Período de Participação</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Projetos em que Participou</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Empresa Atual</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Cargo Atual</label>
        <input type="text"></input>
    </div>
    <div class="element-form">
        <label class="">Redes Sociais</label>
        <input type="text"></input>
    </div>
</form>
