<form>
    <label>Nome Completo</label>
    <input type="text"></input>
    <label>E-mail</label>
    <input type="text"></input>
    <label>RG/Órgão Expedidor</label>
    <input type="text"></input>
    <label>CPF</label>
    <input type="text"></input>
    <label>Endereço Completo</label>
    <input type="text"></input>
    <label>Número de Matrícula</label>
    <input type="text"></input>
    <label>Estado Civil</label>
    <input type="text"></input>
    <label>Telefone</label>
    <input type="text"></input>
    <label>Curso</label>
    <input type="text"></input>
    <label>Cargos Ocupados</label>
    <input type="text"></input>
    <label>Período de Participação</label>
    <input type="text"></input>
    <label>Projetos em que Participou</label>
    <input type="text"></input>
    <label>Empresa Atual</label>
    <input type="text"></input>
    <label>Cargo Atual</label>
    <input type="text"></input>
    <button>Enviar</button>
    <button>Mudar Senha</button>
    <button>Deletar</button>
</form>
